# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo  
        uses: actions/checkout@v4

    #   - name: setup R (remember to set PATH="$HOME/R-4.2.2/bin:$PATH" in .bashrc)
    #     run: |
    #         cd /home/shiny_species/
    #         wget https://cran.r-project.org/src/base/R-4/R-4.2.2.tar.gz
    #         tar -zxf R-4.2.2.tar.gz
    #         cd /home/shiny_species/R-4.2.2
    #         ./configure
    #         make -j8
    #     shell: bash

      - name: Restore renv packages
        uses: r-lib/actions/setup-renv@v2

      - name: Restore renv in deploy directory
        run: |
          renv::restore(prompt=FALSE)
          # /home/shiny_species/actions-runner/_work/_temp/renv/cache/v5/R-4.2/x86_64-pc-linux-gnu
          # /home/shiny_species/actions-runner/_work/shiny_species/shiny_species/renv/library/R-4.2/x86_64-pc-linux-gnu
          # cp -R  ${{ env.RENV_PATHS_ROOT }} /home/shiny_species/actions-runner/_work/shiny_species/shiny_species/renv 
        shell: Rscript {0}

      - name: Copy .Renviron for test runner
        run: |
          cp  /home/shiny_species/.Renviron .
        shell: bash

      - names: restart shiny server
      # visudo -f /etc/sudoers.d/custom_service_restart
      # shiny_species ALL=NOPASSWD: /usr/bin/systemctl restart shiny-server.service
       run:
        sudo systemctl restart shiny-server.service
        
    #   - name: Install dependencies
    #     run: |
    #       options(repos = c(CRAN = "cran.mirror.rafal.ca"))
    #       install.packages(c("remotes", "rcmdcheck", "testthat"),lib = "~/R/library")
    #       remotes::install_deps(dependencies = TRUE,  upgrade = "never", lib = "~/R/library")
    #     shell: Rscript {0}
